### ISSUE TITLE
Various python errors prevent run.sh from working

### ISSUE THREAD

**Issue by GabMus** [gonzaarcr/Fildem#1]
I tried running `run.sh` like stated in the readme, but there were errors. Here's the output of pyflakes, showing different errors and what not

```
./keybinder.py:4:1 'dbus' imported but unused
./utils/window.py:82:13 undefined name 'self'
./utils/window.py:83:4 local variable 'signal' is assigned to but never used
./utils/window.py:100:37 undefined name 'window_data'
./utils/window.py:100:18 undefined name 'window_data'
./utils/window.py:102:40 undefined name 'window_data'
./utils/menu.py:7:1 'gi.repository.Gio' imported but unused
./utils/menu.py:9:1 'gi.repository.GLib' imported but unused
./utils/menu.py:11:1 'utils.fuzzy.match_replace' imported but unused
./utils/menu.py:208:3 local variable 'signal' is assigned to but never used
./utils/menu.py:281:4 local variable 'e' is assigned to but never used
./utils/menu.py:318:3 local variable 'signal' is assigned to but never used
./utils/appindicator.py:8:1 'gi.repository.Gdk' imported but unused
./utils/appindicator.py:59:3 local variable 'ac' is assigned to but never used
./handlers/global_menu.py:10:1 'gi.repository.GLib' imported but unused
./handlers/global_menu.py:11:1 'gi.repository.GObject' imported but unused
./handlers/global_menu.py:13:1 'utils.service.BUS_NAME' imported but unused
./handlers/global_menu.py:13:1 'utils.service.BUS_PATH' imported but unused
./handlers/global_menu.py:14:1 'utils.fuzzy.FuzzyMatch' imported but unused
./handlers/global_menu.py:15:1 'utils.fuzzy.normalize_string' imported but unused
./handlers/global_menu.py:16:1 'utils.fuzzy.match_replace' imported but unused
./handlers/global_menu.py:234:3 local variable 'tstamp' is assigned to but never used
./handlers/global_menu.py:253:3 local variable 'tstamp' is assigned to but never used
./handlers/global_menu.py:319:3 local variable 'ac' is assigned to but never used
```

**Comment by gonzaarcr** [comment]
Thanks! The unused stuff will remain there probably, I tend to leave it as “documentation”. When you are working with undocumneted stuff a well named variable is worth it.

You are using Wayland, right?

**Comment by gonzaarcr** [comment]
Fixed https://github.com/gonzaarcr/Fildem/commit/b4633aa961567c65703f43c38fd270c40f2370ad https://github.com/gonzaarcr/Fildem/commit/32c6fe11d8992ddf2c4043ca477121d80586f726

**Comment by ModernMozart** [comment]
Hi!

I'm having issues with the installation. When I try to run "run.sh" it tells me that fuzzysearch isn't found, but when I run pip3 install fuzzysearch the output is

Requirement already satisfied: fuzzysearch in /home/<user>/.local/lib/python3.8/site-packages (0.7.3)
Requirement already satisfied: attrs>=19.3 in /home/<user>/.local/lib/python3.8/site-packages (from fuzzysearch) (20.2.0)

so it's apparently installed, but run.sh can't find it. Any ideas or fixes?

![Untitledscreen](https://user-images.githubusercontent.com/73030322/96346479-e0361180-1050-11eb-8eb5-4602387598f0.png)
