### ISSUE TITLE
The labels for the global menu items are being cut of and replaced with "."

### ISSUE THREAD

**Issue by TheBlueOompaLoompa** [gonzaarcr/Fildem#102]
### Information

- **Operating System**:  Artix Linux
- **Gnome Shell Version**: 40
- **Xorg/Wayland?**: Xorg
- **Apps tested**:  VSCodium
- **Fildem version**: latest

### What is the current behavior?

All menu labels are just dots,
![image](https://user-images.githubusercontent.com/53215039/129661205-ab560645-52f2-4012-88a7-92e9f461599c.png)
also if I set the button paddings to 0 it will show the shortest word for label which is `go`.
![image](https://user-images.githubusercontent.com/53215039/129661406-2a012abe-405d-4581-9a46-fec127fe2753.png)

### Steps to reproduce the problem

Install the extension and launch VSCodium

### What is the expected behavior?

It should show the menu labels without cutting them off so early

**Comment by karyan40024** [comment]
I guess you have **[Scroll Panel](https://extensions.gnome.org/extension/4257/scroll-panel/)** extension installed. 
If so then go to extension **Settings** > **Switching Windows** > uncheck **Panel fixed width**.
