### ISSUE TITLE
Menus dropdowns in second monitor.

### ISSUE THREAD

**Issue by caglarbingol** [gonzaarcr/Fildem#11]
When menu items on panel but dropdown menus on second monitor. I use manjaro.

**Comment by llgdd** [comment]
Same issue here, global app menu is in the top bar, but the dropdowns are on the second display. Ubuntu 20.04 LTS, Gnome 3.36.

![image_2021-01-03_23-53-02](https://user-images.githubusercontent.com/53429650/103489691-d9809480-4e1e-11eb-83af-28e89a5c5ebc.png)

**Comment by gonzaarcr** [comment]
Fixed on 6f8903f. I changed it to always appear on the primary monitor since there’s only a panel on the primary

**Comment by caglarbingol** [comment]
then i close this issue.
