### ISSUE TITLE
Need to hover over top bar once to display global menu

### ISSUE THREAD

**Issue by uxdiin** [gonzaarcr/Fildem#12]
I need to hover the top bar a single time every time I change the app to show the global menu bar. I have changed. I've changed FORCE_SHOW_MENU in extensions.js to true. Please help. Thanks.

**Comment by gonzaarcr** [comment]
Did you reset the gnome-shell? (`Alt+F2`, then you type `r` and enter)

**Comment by uxdiin** [comment]
> Did you reset the gnome-shell? (`Alt+F2`, then you type `r` and enter)

yes I've done that

**Comment by nayaabkhan** [comment]
Same problem on my side :+1: 

Running Pop OS 20.10.

**Comment by gonzaarcr** [comment]
Fixed on 1adc4ec together with some bugs with the overview and when showing desktop.

**Comment by uxdiin** [comment]
> Fixed on [1adc4ec](https://github.com/gonzaarcr/Fildem/commit/1adc4ecbde67c981f3f36ae5a861443807da5ff1) together with some bugs with the overview and when showing desktop.

Work great. Thanks!
