### ISSUE TITLE
Missing menu

### ISSUE THREAD

**Issue by greyhatguy007** [gonzaarcr/Fildem#125]
### Information

- **Operating System**:  Pop!_OS 21.10 
- **Gnome Shell Version**:  40.5
- **Xorg/Wayland?**:  Xorg
- **Apps tested**: Visual Studio Code
- **Fildem version**:0.6.7
### What is the current behavior?
Fildem global menu not showing anything in the top panel. Existing normal panel also vanished.

### Steps to reproduce the problem
No idea

### What is the expected behavior?
Global menu expected. The current normal menu is vanished but it is not seen in the top panel, no matter what I do.
![Screenshot from 2022-01-15 20-18-34](https://user-images.githubusercontent.com/77543865/149626089-4889fbcb-d7a8-48c3-92e9-5807aa5fc635.png)

**Comment by Dargh-Lenoule** [comment]
this is connected to the python update. if you try running fildem in the terminal, it will print out the error
