### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by aliuselly** [gonzaarcr/Fildem#14]
Hello, I can’t find unity-gtk2-module unity-gtk3-module during installation. I have a Debian 10 gnome 3.38.1 system. Can I use this plugin?

**Comment by gonzaarcr** [comment]
Maybe you don’t need them on Debian, I haven’t tested. Try installing `appmenu-gtk-module-common appmenu-gtk2-module
appmenu-gtk3-module`.

**Comment by aliuselly** [comment]
Oh, thanks, I'll try it later!2020年11月12日 05:42，Gonzalo <notifications@github.com>写道：

Maybe you don’t need them on Debian, I haven’t tested. Try installing appmenu-gtk-module-common appmenu-gtk2-module appmenu-gtk3-module.

**Comment by aliuselly** [comment]
> Maybe you don’t need them on Debian, I haven’t tested. Try installing `appmenu-gtk-module-common appmenu-gtk2-module appmenu-gtk3-module`.

Hello, I installed the pre-installation according to your requirements, but the following exception occurred when running ./run.sh, but I don’t understand python. However, I used pip3 to install these dependent libraries. They all seem to be Error and non-existence: HudMenu, FuzzyMatch, find_near_matches.

./run.sh: 第 3 行：[: =：需要一元表达式
Traceback (most recent call last):
  File "./command.py", line 7, in <module>
    from handlers.default import HudMenu
  File "/home/aliuselly/Global Menu/Fildem/handlers/default.py", line 13, in <module>
    from utils.fuzzy import FuzzyMatch
  File "/home/aliuselly/Global Menu/Fildem/utils/fuzzy.py", line 3, in <module>
    from fuzzysearch import find_near_matches
ModuleNotFoundError: No module named 'fuzzysearch'

**Comment by gonzaarcr** [comment]
You have to install `fuzzysearch` with `pip3 install fuzzysearch`. And you don’t have to run it with `sudo`.

**Comment by aliuselly** [comment]
> You have to install `fuzzysearch` with `pip3 install fuzzysearch`. And you don’t have to run it with `sudo`.

Oh, thank you very much, I really did not expect to be able to implement the global menu on the new version of gnome, I have been looking for it for a few months, thanks! ! !
