### ISSUE TITLE
Doesn't work with Gnome 42?

### ISSUE THREAD

**Issue by hrqmonteiro** [gonzaarcr/Fildem#148]

**Comment by hrqmonteiro** [comment]
?

**Comment by hrqmonteiro** [comment]
?

**Comment by kttary** [comment]
Unzip fildemGMenugonza.com.v2.shell-extension.zip 
Edit metadata.json file and add “42”
Zip the files back 
Run gnome-extensions install ./that_modified.zip
Restart gnome

im running fildem on gnome 42 without any problem but android studio menu

**Comment by Fuseteam** [comment]
seems to be added in the repo already https://github.com/gonzaarcr/Fildem/blob/dcd77d170822024ed7fc3c3781b3b77d1f076183/fildemGMenu%40gonza.com/metadata.json#L10 i wonder why we don't see it in extension manager
