### ISSUE TITLE
Unable to launch from anywhere but terminal

### ISSUE THREAD

**Issue by Vencorr** [gonzaarcr/Fildem#15]
I'm at a huge loss and cannot figure this out.

I'm running RebornOS (AKA Manjaro but not), and have looked at #5 to help with dependency problems and all.

Now it works! Except with the big problem as it just refuses to launch from anywhere besides the terminal. I've never had this issue with anything before. Trying to run it anywhere but in the command-line just results in nothing.

I'm just trying to add this to an autostart desktop entry. I would prefer not having to keep a terminal open.

**Comment by gonzaarcr** [comment]
I’m planning to do a service but I don’t know how many distributions use systemd

**Comment by gonzaarcr** [comment]
Okay, I think a service is not possible, it would be overcomplicate the stuff. I changed some stuff and it seems it works on startup.

**Comment by Vencorr** [comment]
Problem seems fixed. Able to start it up now without even touching the terminal anymore.
