### ISSUE TITLE
Start the script at boot

### ISSUE THREAD

**Issue by aliuselly** [gonzaarcr/Fildem#16]
Hello, after successfully using your script, I started to study how to start your script at boot, but all failed. Therefore, I would like to ask how you solved the problem of booting the script. My questions are as follows: When the script is started on boot, the sudo permission is used, and the script running under this permission fails.

**Comment by gonzaarcr** [comment]
Hello. That’s probably the next step. I’m probably gonna do it with a service, I hope all the distro play well with that...

**Comment by aliuselly** [comment]
> Hello. That’s probably the next step. I’m probably gonna do it with a service, I hope all the distro play well with that...

Oh, thank you, I am looking forward to the next version.

**Comment by gonzaarcr** [comment]
A service and a package (that I had in mind) is overkilling. I changed some stuff and it works on startup. Let me know if you have some issue.

**Comment by aliuselly** [comment]
Hello, I cloned your Fildem project again, and then reinstalled it again, but there was a problem, as follows:
================================================= ====
ERROR:dbus.connection:Unable to set arguments (0, -1, []) according to signature None: <class'ValueError'>: Unable to guess signature from an empty list
Traceback (most recent call last):
  File "/home/aliuselly/Global_Menu/Fildem/utils/window.py", line 119, in _window_switched_bamf
    cls._call_all_listeners(win)
  File "/home/aliuselly/Global_Menu/Fildem/utils/window.py", line 129, in _call_all_listeners
    callback(window)
  File "/home/aliuselly/Global_Menu/Fildem/utils/menu.py", line 274, in on_window_switched
    self._init_window()
  File "/home/aliuselly/Global_Menu/Fildem/utils/menu.py", line 270, in _init_window
    self._update()
  File "/home/aliuselly/Global_Menu/Fildem/utils/menu.py", line 331, in _update
    self._update_menus()
  File "/home/aliuselly/Global_Menu/Fildem/utils/menu.py", line 328, in _update_menus
    self.appmenu.get_results()
  File "/home/aliuselly/Global_Menu/Fildem/utils/menu.py", line 231, in get_results
    results = self.interface.GetLayout(0, -1, [])
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 72, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 643, in call_blocking
    message.append(signature=signature, *args)
ValueError: Unable to guess signature from an empty list
================================================= ====
(Opening vs code everything is normal, but when opening chrome, there is an error below. At the same time, the terminal running ./run.sh is stuck. |||| However, the version of 2020.11.12 I used before is all perfect )
Finally, although you said that you have added a boot, but I don’t know how to enable it. I hope you can tell me.

**Comment by gonzaarcr** [comment]
That bug was added when I fix the electron menus. I don’t know why I can’t replicated it, maybe cache. It should work know with the last commit (bff21c6).

For the start up script I used gnome-session-properties, but it can also be done with gnome-tweak-tools. It should create a .desktop file on `~/.config/autostart/`.

**Comment by aliuselly** [comment]
> That bug was added when I fix the electron menus. I don’t know why I can’t replicated it, maybe cache. It should work know with the last commit ([bff21c6](https://github.com/gonzaarcr/Fildem/commit/bff21c6bb865d3583a58994f3cba7b3063c13222)).
> 
> For the start up script I used gnome-session-properties, but it can also be done with gnome-tweak-tools. It should create a .desktop file on `~/.config/autostart/`.

Hello, thank you for your reminder. I tried your method, but this is based on the version 2020.11.12. The latest version is not used because of some bugs. However, I still fail when I boot up. I feel so tired now ,details as follows:
1. I first used your suggestion: gnome-session-properties, but: command not found: gnome-session-properties, I checked, it seems to be a gnome version problem, my version is gnome 3.38.1
2. Then, I used the desktop method, but it didn't work (my system is Debian 10 gnome 3.38.1), as follows:
`GlobalMenu.desktop file`
===
```
[Desktop Entry]
Encoding=UTF-8
Name=GlobalMenu
Comment=My Global Menu
Type=Application
Icon=/home/aliuselly/v6.png
Exec=bash -c "/home/aliuselly/Global_Menu/Fildem2/run.sh"
Terminal=false
Categories=Application;Programme;
```
===
`~/Global_Menu/Fildem2 directory`
===
```
-rw-r--r-- 1 aliuselly aliuselly 516 November 11 14:17 appmenu.py
-rw-r--r-- 1 aliuselly aliuselly 1017 November 11 14:17 command.py
drwxr-xr-x 2 aliuselly aliuselly 4096 November 11 14:17'fildemGMenu@gonza.com'/
drwxr-xr-x 3 aliuselly aliuselly 4096 November 11 15:06 handlers/
-rw-r--r-- 1 aliuselly aliuselly 18 November 11 14:17 __init__.py
-rw-r--r-- 1 aliuselly aliuselly 759 November 11 14:17 keybinder.py
drwxr-xr-x 2 aliuselly aliuselly 4096 Nov 21 16:46 __pycache__/
-rw-r--r-- 1 aliuselly aliuselly 2007 November 11 14:17 README.md
-rwxr-xr-x 1 aliuselly aliuselly 183 November 11 14:17 run.sh*
drwxr-xr-x 3 aliuselly aliuselly 4096 Nov 11 15:06 utils/
```
===
`~/.config/autostart directory`
===
```
-rw-r--r-- 1 aliuselly aliuselly 516 November 11 14:17 appmenu.py
-rw-r--r-- 1 aliuselly aliuselly 1017 November 11 14:17 command.py
-rw-r--r-- 1 aliuselly aliuselly 1006 September 9 09:24 fcitx.desktop
-rw-r--r-- 1 aliuselly aliuselly 222 November 23 15:46 GlobalMenu.desktop
-rw-r--r-- 1 aliuselly aliuselly 208 April 28 2020 goldendict.desktop
drwxr-xr-x 3 aliuselly aliuselly 4096 November 11 15:06 handlers/
-rw-r--r-- 1 aliuselly aliuselly 18 November 11 14:17 __init__.py
-rw-r--r-- 1 aliuselly aliuselly 759 November 11 14:17 keybinder.py
drwxr-xr-x 2 aliuselly aliuselly 4096 Nov 21 16:46 __pycache__/
drwxr-xr-x 3 aliuselly aliuselly 4096 Nov 11 15:06 utils/
```
===
(You may be wondering why a copy of the Fildem project file is under the autstart directory, because I found that command.py in run.sh is a relative path)
I can’t do anything, but thank you for indicating that this method can be achieved, thanks!

**Comment by gonzaarcr** [comment]
I fixed some stuff on the latest vesion, maybe that why it doesn’t work. For example, `run.sh` has now a `cd` to fix the relative path and other stuff. I’m gonna download Debian on a VM and see what I can do.

**Comment by aliuselly** [comment]
> I fixed some stuff on the latest vesion, maybe that why it doesn’t work. For example, `run.sh` has now a `cd` to fix the relative path and other stuff. I’m gonna download Debian on a VM and see what I can do.
> 
> Are you on Wayland or Xorg?

X11, I think it should be XOrg, I don’t think you need to use debian on a virtual machine. In fact, I think you should complete a gnome platform general method. Thank you for your guidance.

**Comment by aliuselly** [comment]
thank you very much! I updated it today. It turned out to be the reason why I didn’t use the new version. Just because of a bug, I missed the boot function of the new version. It is already perfect. However, I have a problem here. Although the operation is perfect, Why doesn't chrome show its menu?

**Comment by gonzaarcr** [comment]
Oh, thanks, I just fixed it. I think the fix for Brave broke it.

**Comment by aliuselly** [comment]
> Oh, thanks, I just fixed it. I think the fix for Brave broke it.

Nice! Very, very perfect, chrome is now perfectly displayed and used, it will not get stuck, thank you again, thank you! ! !
