### ISSUE TITLE
hello guys! unity-gtk3-module&appmenu-gtk3-module, ubuntu20.04 can not install the modules at the same time! they collision mutually!

### ISSUE THREAD

**Issue by honglongyu** [gonzaarcr/Fildem#17]
hi,boys and girls,solve the problem with your wisdom!

**Comment by gonzaarcr** [comment]
Try installing only these four `unity-gtk-module-common appmenu-gtk-module-common appmenu-gtk2-module appmenu-gtk3-module`.
