### ISSUE TITLE
Menu item not corresponding spacially

### ISSUE THREAD

**Issue by carallo** [gonzaarcr/Fildem#18]
Hello!
finally someone tried again to giva a globalmenu to Gnome Shell, god bless you! Thank you so much!
Starting using it now, I have a couple of questions.

Firstly, I'm having some visual issues. The most important is that the menus don't always exactly correspond with the item I select, I'm having this problem especially with VLC, less on Libreoffice, wierdly. It seems like the menu items visible on the bar don't correspond spacially with the actual buttons (I attach an image, cannot see the cursor but it actually was on the "video" menu item, while the "subtitles" menu was appearing).

![Schermata da 2020-11-27 14-53-44](https://user-images.githubusercontent.com/32939683/100457197-e5f82b80-30c1-11eb-8f66-40d2135b2576.png)
 
Also I'm using the same Gnome-shell theme as in your screenshot, Yaru-dark, but I don't see the buttons as themed as yours. I don't know if this is relevant, I just say it because once, opening VLC, I saw the menu "yaru-themed" for some seconds and the buttons indeed seemed to correspond. I haven't been able to reproduce this again though.

Second thing, I cannot seem to have the HUD working, alt-space just opens the standard window menu. I'm mentioning this in case it could be related to the other issue, it's not really fundamental for me as I don't use this function so much.

BTW thank you so much again!

EDIT: well, while switching to VLC to take the screenshot actually the themed menu appeared again for some seconds and the menu items rightly corresponded. It's like something is drawing other menu items over the top bar, hiding the "right" ones.

![Schermata da 2020-11-27 15-01-40](https://user-images.githubusercontent.com/32939683/100457397-42f3e180-30c2-11eb-9dd7-c50708a72f1e.png)

EDIT 2: If of any interest, I get this error in terminal : 
`(-c:21173): Gtk-WARNING **: 14:46:44.872: no trigger event for menu popup`

**Comment by gonzaarcr** [comment]
Yes, the program is another menu, and the solution to “integrate” to the shell was to show the menus also on the top bar. The menu is set to appear transparent, it look worse this way but it really hard to integrate the theme. If you want to remove the transparency yo can remove the line [self.window.make_transparent()](https://github.com/gonzaarcr/Fildem/blob/master/handlers/global_menu.py#L377).
 Other solution is to reduce the spacing between the items as the README says, or modifying the padding on [extension.js](https://github.com/gonzaarcr/Fildem/blob/master/fildemGMenu%40gonza.com/extension.js#L23).
 Yeah, I’m still thinking on better ways to integrate it.

 The HUD was my mistake, I removed some imports on hte last commit, it fixed.

 And the warning is normal.

**Comment by carallo** [comment]
Hey @gonzaarcr thanks for the fast reply!
I had already tried the workaround of the README and it didn't help much, but now I might try to tinker with the padding settings.

Anyway I didn't understand why you are drawing another menu over the already present menu. I've removed the [self.window.make_transparent() ](https://github.com/gonzaarcr/Fildem/blob/master/handlers/global_menu.py#L377) line and now it actually disappear when I hover with the mouse, but I have to say that, with my settings, the menu that appears underneath is actually perfect, it would be enough with that.
Is there a way to completely remove the overlying menu and just leaving the underlying one? Or is there any specific reason for the other being there?

Thank you again!

**Comment by gonzaarcr** [comment]
The real menu is the one that is drawn above. That contains all the menu items. The one on the shell is because I couldn’t integrate it with the shell /: You can’t create menu items on the gnome shell, or if you want to do it you have to do it from scratch (which is suicidal because the shell code changes every couple of month, so it will break really often).

If I have time I will make a wiki for developers.

**Comment by carallo** [comment]
Ah ok! So actually the "themed one" (let's call it like that, the second picture I have attached before) is drawn over the other text, that you have put on the shell just to be able to see the menu items. Sorry for bothering, I'm not a developer, I just like to tinker around and I'm trying to understand how this app works since I cannot get it from the code, due to my ignorance.
So you put this text on the top bar, and when I click on it it then loads the "real" menu (the themed one). Did I get it right?

Anyway, I'll just try the spacing settings now to see if I find a satisfying one. I still don't understand how Gnome devs can make it this hard to have a Global Menu, since it's such an ergonomic UX design.

**Comment by gonzaarcr** [comment]
Yes, you understood everything right. And if you are wondering why not leaving the “real” menu always and not have the fake one, is because you cannot click it if it’s above the panel.

**Comment by carallo** [comment]
Hey @gonzaarcr, sorry for bothering again. 
I have a problem now, I don't know if it depends from system update of the last days actually. Anyway, all of a sudden, the "real" menu now has moved a bit to the left (or the other one to the right, who knows), so they don't coincide anymore. I've tried fiddling with settings but I couldn't find a way to move it a bit more rightwards, is there a line I should edit for that?

**Comment by gonzaarcr** [comment]
Can confirm. It seems to happen when the programm is used for long time and dissapears when the shell is restart (so, that’s why I didn’t see it, I restart every 5 min).

**Comment by gonzaarcr** [comment]
I confirm is the screen turning off. It seems gnome disables and re-enables all the extension, even if you didn’t log out.. It also causes another bug where you don’t have the menu on the app that is open, you need to change windows to see it.

**Comment by carallo** [comment]
> I confirm is the screen turning off. It seems gnome disables and re-enables all the extension, even if you didn’t log out.. It also causes another bug where you don’t have the menu on the app that is open, you need to change windows to see it.

Now I see! I was experiencing the disappearing bug too actually. Does this only happen in Wayland?
I'll see if I can replicate it, focusing on the turning off of the screen. Strange behaviour though, to restart all extensions...
Thank you so much for digging into the issue!

**Comment by gonzaarcr** [comment]
I just changed the behaviour on d0dc530, now it doesn’t show text so it should work even after the shell restart; but I’ll keep on testing.

**Comment by carallo** [comment]
Sorry @gonzaarcr , haven't got the time to try the fix yet, will check tonight!

**Comment by carallo** [comment]
Just tried it out, the behaviour seems somewhat more reliable now I have to say.

One thing that still keeps happening to me, even though it's not so annoying for my workflow, is that often the menu sticks on the top bar even when changing or closing the app. And I haven't found a way to replicate this in a meaningful manner, it seems very random, it sometimes disappears as it should, sometimes sticks for a long time, sometime just some seconds.

**Comment by gonzaarcr** [comment]
Iteresting. Thank you for reporting all these little details. I’m thinking on implementing a chace to optimize the window switching but I really have to test it. Working with so many programs and the shell at once is the perfect scenario for unexpected errors.

**Comment by carallo** [comment]
> Iteresting. Thank you for reporting all these little details. I’m thinking on implementing a chace to optimize the window switching but I really have to test it. Working with so many programs and the shell at once is the perfect scenario for unexpected errors.

No worries, actually thank you for continually improving Fildem!
I can help you testing, I have not too much time but I can try as fast as I can eventual patches and commits!

**Comment by 12gabriel3** [comment]
I have this issue too
Ubuntu 20.04 
Dracula theme

**Comment by gonzaarcr** [comment]
You can tweak the padding of the butons (here)[https://github.com/gonzaarcr/Fildem/blob/master/fildemGMenu%40gonza.com/extension.js#L23].

**Comment by 12gabriel3** [comment]
> You can tweak the padding of the butons (here)[https://github.com/gonzaarcr/Fildem/blob/master/fildemGMenu%40gonza.com/extension.js#L23].

Do you suggest any values or have some tips? I have tried many values now, but they are always off. Also I'm not really sure what exactly the values do.
![menu](https://user-images.githubusercontent.com/16885097/109577128-d7ac1800-7ad3-11eb-8e6d-8c4246d94880.gif)

**Comment by gonzaarcr** [comment]
I should take the time to add preferences to the extension, but I’m always switching task :/

**Comment by gonzaarcr** [comment]
I added settings to the extension, so this is easy configurable now.

**Comment by nekkan** [comment]
I am having the same problem here on Ubuntu 20.10.
