### ISSUE TITLE
There is a space between app name and menu

### ISSUE THREAD

**Issue by caglarbingol** [gonzaarcr/Fildem#2]
I use Manjaro and there is some bug in this extension. I try your extension. Good one btw. Skype dont show global menu and there is a space between appname and menu https://ibb.co/xHGf8vW

**Comment by gonzaarcr** [comment]
Yes, that it’s intended, I had to select a fixed position, which is 400. I should add a way to change it, but I would need more information about screens. I select a big number thinking on the little screens which are the one that most need this functionality. How big is your screen?

**Comment by caglarbingol** [comment]
My screen 15.6'' and resolution is 1366x768. You should add a way to change it in my opinion. 

I'm not good at github. I'm thinking to use gitlab but its your decision.

Skype has no change long story short.

Btw most of users wait for this extension. You should add this to gnome extensions website. I comment ex extension of global menu extension to link this. I hope they reach this and help you. Good luck with that. And people gonna love it imo.

**Comment by caglarbingol** [comment]
I change space with extention.js but i realize when i click an a item there is new panel show up. I dont know what is it and cant screenshot when it appear. maybe you wanna know it.

**Comment by gonzaarcr** [comment]
Yes, that is the menu. It was the only way of integrate it. I suspected you hadn’t open it since you didn’t mention the mismatch colour.

**Comment by caglarbingol** [comment]
my theme same color i didn't realize it. Sorry about that. can i change location of it? and sorry about my english?

**Comment by caglarbingol** [comment]
and thanks for extensions i wait for long time it

**Comment by gonzaarcr** [comment]
I added some dynamic positioning on this [commit](https://github.com/gonzaarcr/Fildem/commit/c4ffebbb474c0810d58488d291696b1a75dcfb46), try it and tell me the results.

**Comment by caglarbingol** [comment]
In shell panel the other menu appears where i click. for example if i click file menu in gnome panel, app menu appears right in front of panel menu (which i like it) but if i click edit in gnome menu, app menu's file menu begin with edit menu in gnome panel. i hope i can able to tell.

**Comment by gonzaarcr** [comment]
Yes, the menu works by syncing those two menus. I made it transparent on 2c64e91 after giving up to theme it properly.
