### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by OfficialOzioma** [gonzaarcr/Fildem#20]
###  Please Help me
Hello please I'm new to linux OS, and and I'm using Ubuntu 20.04, 
i will like to implement this global menu on my PC too, but i don't know where or how to start.

First i have installed all the extension in **Issue #17** 
And i have cloned this repo into my pc.
I have also done that setup in the read me of this repo

what is the next thing i need to do so that menu will appear and start working.\

i will appreciate any help

thanks so much

**Comment by gonzaarcr** [comment]
It’s hard to know what exactly you are missing, but if you have done all the step on the read me here are some things to check:

- Not every program export their menus, so make sure to test with some that does it (all qt do, like vlc or clementine; gedit also exports them).
- Make sure the extension is installed and activated (go to the extensions app to check).
- Make sure the `run.sh` program is running.
- Some programs need to be opened after the `run.sh` is executed.
- The menu is only shown when the mouse is hover the panel by default, so check that.

**Comment by tiotrom** [comment]
Same here.

When I run the run.sh, I do so from the folder I downloaded from here right? But I get this:

```
[tio@tio-gl753vd Fildem-master]$ ./run.sh
Traceback (most recent call last):
  File "./command.py", line 6, in <module>
    from handlers.default import HudMenu
  File "/home/tio/Downloads/Fildem-master/handlers/default.py", line 16, in <module>
    from utils.menu import WindowActions
  File "/home/tio/Downloads/Fildem-master/utils/menu.py", line 10, in <module>
    from utils.window import WindowManager
  File "/home/tio/Downloads/Fildem-master/utils/window.py", line 4, in <module>
    gi.require_version('Bamf', '3')
  File "/usr/lib/python3.8/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Bamf not available

```

I am on Manjaro Gnome

**Comment by gonzaarcr** [comment]
You have to install Bamf. It should work with `pacman -S bamf`

**Comment by tiotrom** [comment]
> You have to install Bamf. It should work with `pacman -S bamf`

It is installed...

**Comment by gonzaarcr** [comment]
Okay, let me downlaod a vm then, I’ve never tried Manjaro. Wayland or Xorg?

**Comment by tiotrom** [comment]
Xorg

**Comment by gonzaarcr** [comment]
It does work for me in a brand new install, I don’t know what is the problem.

**Comment by tiotrom** [comment]
I tried it again in a VM and I failed to make it work. Can you please provide the step by step of what you did to make it work in Manjaro? I followed all the instructions from the homepage.

**Comment by gonzaarcr** [comment]
I literally just pasted the instructions for Arch and it worked. Qt4 apps may need a fix, but there’s no error in the program.

**Comment by tiotrom** [comment]
Ok. I am doing it step by stem with Manjaro Gnome:

1. I download this repo and install the extension copying/moving the fildemGMenu@gonza.com folder into ~/.local/share/gnome-shell/extensions

2. I go to the downloaded original folder of this repo, and I open it in terminal and do: ./run.sh and I get this:
![image](https://user-images.githubusercontent.com/34804533/101426559-82f66800-38fd-11eb-8991-d8322f246d55.png)

Is that ok? I want to know what I should do next, if I should continue with doing the next steps.

**Comment by tiotrom** [comment]
I continue nevrtheless:

3. I install these: pacman -S bamf appmenu-gtk-module libkeybinder3 libdbusmenu-gtk2 libdbusmenu-gtk3 libdbusmenu-qt5

4. In my home folder I create a file named ".gtkrc-2.0" and inside this text file I add: gtk-modules="appmenu-gtk-module"

5. I create another text file in ~/.config/gtk-3.0/ called "settings.ini" and inside it I paste this: 
[Settings]
gtk-modules="appmenu-gtk-module"

6. I enable the extension form the Extension panel.

7. I restart the shell.

Nothing. Nothing works. I even rebooted the VM... I opened many applications. No global menu, no HUD...

**Comment by gonzaarcr** [comment]
Install it with pip, `pip3 install fuzzysearch`. The “dependencies” part wasn’t supposed to related to Ubuntu. I’m gonna modified the README, sorry the confusion.

**Comment by tiotrom** [comment]
Ok thanks we are getting somewhere :).

So. I installed `pip3 install fuzzysearch` and now it works to run the `./run.sh` . However there is no global menu on most applications. Or HUD for that matter.
 I get the message: 
![image](https://user-images.githubusercontent.com/34804533/101488284-b1a52a80-395f-11eb-95e9-8c2b646cdcc5.png)
GIMP, Gedit work, but not the others.... Why is that?

Second, you always have to do `./run.sh` from the downloaded folder for it to work?

**Comment by tiotrom** [comment]
Update: after a reboot and all that, many applications work, but others do not.

Applications that do not work are: Audacity, Krita (flatpak), many Gnome apps like GThumb/Files/Gnome Web/DejaDup/Disks, Thunderbird, QTox, Pitivi, Cheese, and also LibreOffice Writer (Draw and other work).

And after I tested a few applications it stopped working with this error:
```
[tio@tio-gl753vd global-menu]$ ./run.sh
./run.sh: line 6: [: =: unary operator expected
Traceback (most recent call last):
  File "./command.py", line 6, in <module>
    from handlers.default import HudMenu
  File "/home/tio/global-menu/handlers/default.py", line 16, in <module>
    from utils.menu import WindowActions
  File "/home/tio/global-menu/utils/menu.py", line 10, in <module>
    from utils.window import WindowManager
  File "/home/tio/global-menu/utils/window.py", line 18, in <module>
    backend = os.environ['XDG_SESSION_TYPE']
  File "/usr/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'XDG_SESSION_TYPE'

```

**Comment by tiotrom** [comment]
Update: Works for LibreOffice Writer after I called the HUD...maybe takes longer.

The reason I am so interested in this is because I want to test the essence out of it since if all works fine I want to integrate it into out custom Linux, TROMjaro. I love the utility of it all. Thanks a lot for doing this. My concern is that Gnome will break this one very soon, like they always do.

**Comment by tiotrom** [comment]
I am taking notes of all I do, and eventually, if all works fine, we will make an AUR package that should do all of the install, together with creating a .desktop file or a way for the script to start at boot automatically and all that. So we make it super easy for people to install this. But let's properly test it first.

**Comment by gonzaarcr** [comment]
To start at boot you can simply put the path onto gnome-session-properties, it will create the .desktop and execute it at startup.

Yes, it doesn’t work on all the apps. The app has to have a menu and export it, otherwise there won’t be a menu. Gtk apps do not tend to have a menu, they went for the hamburguer menu in the header bar. Qt apps do tend to have and export a menu, try installing `libdbusmenu-qt4` (or `appmenu-qt4`) from aur to see if there’s more Qt apps with menu. For Firefox there’s a patched [version on aur](https://aur.archlinux.org/packages/firefox-appmenu-bin), I guess there’s probably one for thunderbird too.

That error is weird, I’m gonna try to replicate it.

**Comment by tiotrom** [comment]
> To start at boot you can simply put the path onto gnome-session-properties, it will create the .desktop and execute it at startup.

Yup, or create a desktop file with:
```
[Desktop Entry]
Encoding=UTF-8
Name=GlobalMenu
Comment=TROMjaro Global Menu
Type=Application
Icon=global-menu-and-hud
Exec=bash -c "add here the path where the run.sh file is"
Terminal=false
Categories=Application;Programme;
```
And add it to .local/share/applications

Can't you make it work without this somehow?

**Comment by tiotrom** [comment]
As for some apps not working, I have those packages installed but still Krita does not work, or Audacity, and these are not Gtk apps as far as I know. Or am I wrong...

**Comment by gonzaarcr** [comment]
For Krita try installing the libraries mentioned above, it seems Manjaero doesn’t have Qt4 libraries related on their repos. Audacity uses wxWidget, maybe there’s some setting; I’m gonna dig further.
