### ISSUE TITLE
Change the HUD keys

### ISSUE THREAD

**Issue by tiotrom** [gonzaarcr/Fildem#23]
How can we change the HUD activation keys to something else?

**Comment by gonzaarcr** [comment]
[Here](https://github.com/gonzaarcr/Fildem/blob/master/keybinder.py#L21)

**Comment by tiotrom** [comment]
Thanks! Maybe would be a good idea to add this as an option if you ever package this for the gnome extensions website.

**Comment by gonzaarcr** [comment]
Yeah, but as you can see, I’m still fixing errors. Btw, I forgot to mention, to use the control key you have to write `<Primary>`.

**Comment by tiotrom** [comment]
I tried to only use the Alt key or the CTrl key, but it didn't work. Nota  big deal, probably it is a conflict with the system itself that uses these keys. Thanks!

**Comment by gonzaarcr** [comment]
Let me know if it doesn’t work

**Comment by tiotrom** [comment]
I tried with 'Alt' and '<Alt>' or 'Primary' and '<Primary>', and they do not work. In combo with other keys they do, but alone they do not. Since the Alt key is such an important key in Linux, then probably that's the cause.

**Comment by gonzaarcr** [comment]
Oh, you are looking for the Unity behaviour, right? Yeah, since it’s a modifier key I don’t think that’s posible (at least not that easy).

**Comment by tiotrom** [comment]
Yes that's what I was trying to do. Is not a big deal tho.
