### ISSUE TITLE
Export the menu to top panel only when maximized

### ISSUE THREAD

**Issue by tiotrom** [gonzaarcr/Fildem#25]
I was wondering if it would be possible to only export the menu to the top panel when the window is maximized. Could be a cool little option to have.

**Comment by gonzaarcr** [comment]
Nope, for most app the menu is exported at startup and they break if you stop the service while they are running.

**Comment by tiotrom** [comment]
Ok. Because from my tests, with apps open, I could switch without a problem. From global menu, to no global menu, and all worked great and super fast. I could test that more if you are interested in this idea. is not that important, but I thought it may be an interesting option to have.

**Comment by gonzaarcr** [comment]
I could *try* to replace the window menu for a global menu, but then I would have to put that menu somewhere

**Comment by tiotrom** [comment]
I was thinking to leave the menu wherever it is originally, and only add it to the top panel if the window gets maximized. As an optional thing maybe. Could be an interesting and original approach.

**Comment by lestcape** [comment]
> I was thinking to leave the menu wherever it is originally, and only add it to the top panel if the window gets maximized. As an optional thing maybe. Could be an interesting and original approach.

This need to have support in appmenu-gtk-module, in qt and in all other external packages that this project use to make that possible. Here you have only a **client** task. Ofcourse fix all the **server** implementations to make this possible is a hard task.
