### ISSUE TITLE
Global Menu for Jetbrains Apps

### ISSUE THREAD

**Issue by erfanmola** [gonzaarcr/Fildem#26]
Hi, AFAIK Jetbrains apps used to integrate with Jayatana in-order to work with vala-panel and etc, since last year they anounced NativeLinuxMenu in their experimental features that is enabled by default, meaning that they do export menu

But i couldn't get Jetbrains Apps Menus working with Fildem, It would be nice to get integrated and im looking forward to it

I also have to mention that Jetbrains Apps are not like other java apps that need Jayatana, they do export their menus themselves, i used to have global menus in xfce using vala-panel-appmenu and having vala-panel-appmenu-registrar

**Comment by gonzaarcr** [comment]
According to [this](https://youtrack.jetbrains.com/issue/IDEA-169904) it doesn’t work on the latest version. And I can confirm it doesn’t work on KDE.

**Comment by erfanmola** [comment]
So it's an issue of Jetbrains, right ? everything is correct in the extensions side ?

**Comment by skewty** [comment]
Has anybody created an issue with JetBrains for this?  It so, it should be linked here.  

Perhaps they will be able to assist in getting this feature working.

**Comment by metenn** [comment]
Not sure what I did, but it works for me, though it shows up as "DBusMenu root" for whatever reason. It's fully functional though.
![image](https://user-images.githubusercontent.com/49620905/103900933-bdb80f80-50f8-11eb-86c6-20c90cf31945.png)

**Comment by erfanmola** [comment]
> Not sure what's up, works for me out of the box, I double checked if I had anything custom like the launch parameters or custom launch scripts, but nothing. Though it shows up as "DBusMenu root" for whatever reason. It's fully functional though. Even the HUD search works.
> 
> ![image](https://user-images.githubusercontent.com/49620905/103900933-bdb80f80-50f8-11eb-86c6-20c90cf31945.png)
> 
> 

What version are you using ?

**Comment by Devansh80** [comment]
Can we take any reference from [this](https://www.jetbrains.com/help/idea/linux-native-menu.html).

**Comment by gonzaarcr** [comment]
I found how to make it work, you have to install the [JavaFX Runtime for Plugins][1] and restart.

[1]: https://youtrack.jetbrains.com/issue/JBR-2945#focus=Comments-27-4601550.0-0

**Comment by erfanmola** [comment]
> I found how to make it work, you have to install the [JavaFX Runtime for Plugins](https://youtrack.jetbrains.com/issue/JBR-2945#focus=Comments-27-4601550.0-0) and restart.

Thanks, It did the trick !

**Comment by syrop** [comment]
I reported a bug against Android Studio. It is now officially fixed:

https://issuetracker.google.com/issues/121304907
