### ISSUE TITLE
Didnot work in popos 20.04

### ISSUE THREAD

**Issue by akash-258** [gonzaarcr/Fildem#27]
I tried the installation instructions but failed to make it work. If you have some more instructions plz tell. The menubar was removed but I couldn't view in the top panel.

**Comment by gonzaarcr** [comment]
Did you installed the extension, restarted the shell and activated it?

**Comment by akash-258** [comment]
Yes, I tried restarting the shell as mentioned (alt+f2 -> r) but no menu in the top panel. If you need further result, please ask. I want it to work.

**Comment by gonzaarcr** [comment]
Go to the extensions app and check if the extension is enabled.

**Comment by akash-258** [comment]
Thank you that worked, working very nice, but they are not having correct spacing. I will try your sol in readme.

**Comment by akash-258** [comment]
Solved the spacing issue by modifying the extension.js as 
`const MIN_PADDING = 0;
const NAT_PADDING = 5;`
