### ISSUE TITLE
Installation problem.

### ISSUE THREAD

**Issue by Devansh80** [gonzaarcr/Fildem#30]
I am unable to install it correctly. I have followed all the instructions, but it still does not work in my system. Can you please make it little bit easy.
OS: Ubuntu 20.04 LTS

**Comment by tiotrom** [comment]
What about this:


1. Download the repo and install the extension copying/moving the `fildemGMenu@gonza.com` folder into `~/.local/share/gnome-shell/extensions`
2. Install:    ` sudo pacman -S bamf appmenu-gtk-module libkeybinder3 libdbusmenu-gtk2 libdbusmenu-gtk3 libdbusmenu-qt5`
3. Install: `pip3 install fuzzysearch`
4. Go to extensions and enable "fildemGMenu"
5. Reboot your computer
6. Go to the repo folder, and from within, open it in terminal then do: `./run.sh`
7. Test to see if works, if not,
8. Reboot.
9. Do step nr 6 again.  If works:
10. Create a .desktop file in .local/share/applications and name it "global-menu-and-hud". Inside it paste this:

```
[Desktop Entry]
Encoding=UTF-8
Name=GlobalMenu
Comment=TROMjaro Global Menu
Type=Application
Icon=global-menu-and-hud
Exec=bash -c "add here the path where the run.sh file is"
Terminal=false
Categories=Application;Programme;[Desktop Entry]
```

11. Save and Alt + F2 the type "r" to reboot the desktop
12. Search in the menu to see if the file is there
13. Via Tweaks add it to Startup at boot

**Comment by gonzaarcr** [comment]
I’m working on packaging, but it won’t solve setup problems, since those have to be done by the user. I just created a [discussion](https://github.com/gonzaarcr/Fildem/discussions/33) to solve this kind of problems without having to use issues. Try to describe what have you reach there. Thanks.

**Comment by Devansh80** [comment]
Thanks! Then i'm closing this issue.
