### ISSUE TITLE
Problems running the extension on Debian

### ISSUE THREAD

**Issue by Sesam31** [gonzaarcr/Fildem#32]
Hi, I recently installed this extension, I have managed to make it work but when i run `./run.sh` nothing comes up on the top bar, furthermore if I press Alt + space it brings up the menu but in the terminal it says: 
`Gnome HUD: WARNING: (Firefox ESR) No menu items available!`
This happens with every application I try to run, any idea of what might be causing it?
Running debian 10 with gnome shell 3.38.2.
Keep up the good work!!!

**Comment by gonzaarcr** [comment]
That means it’s working but the application doesn’t export menus. Try with a Qt app or some that export their menus, like Sublime Text or Gedit.

**Comment by llgdd** [comment]
Is there any possibility to get Firefox menu working with Fildem?

**Comment by gonzaarcr** [comment]
There are patched versions, but I don’t think they can be used on Ubuntu. Another solution is adding the ppa of Ubuntu 16, but it almost at end of support.

**Comment by Sesam31** [comment]
> That means it’s working but the application doesn’t export menus. Try with a Qt app or some that export their menus, like Sublime Text or Gedit.

Thanks for the help!
It works like a charm with gedit but it's pretty much the only application I have that exports the menus.
Is there maybe a way to make it compatible with other application frameworks (GTK, electron,...) ?

**Comment by gonzaarcr** [comment]
It works with Electron apps (I’ve tested VS and Atom at least). Gtk apps generally don’t export menus so no. I’m keeping a list [here](https://github.com/gonzaarcr/Fildem/wiki/Using#state-of-the-apps).

**Comment by Sesam31** [comment]
Ok thanks I didn't notice that part while reading the description, mb.
