### ISSUE TITLE
Text color

### ISSUE THREAD

**Issue by carallo** [gonzaarcr/Fildem#34]
Hi @gonzaarcr , happy new year, I hope you passed nice holidays!

I have a question, I know it depends on the GTK theme but I was wondering if you had some fix or suggestion for it.
Lately I'm using the adwaita theme, which is light during daytime and I have it switch to dark version at night time.
When using the light version, the menu exported by Fildem has dark text, so it's hard to read on the black top panel.
Is there some setting that could be added or edited in Fildem to have the menu exported with another text color or do I need to change the whole theme settings? I would prefer to avoid this way due to updates that might break it again or similar issues.

Thank you again!

**Comment by Vince-bleu** [comment]
For the top bar, you can have a theme different than the gtk i think. In tweaks you can set the theme for the shell.

But i think it could be nice to have a specific color for the menu and/or force them to be regular or bold.
Maybe it's too complicated to overpass the theme css ? Just asking.

**Comment by gonzaarcr** [comment]
You want it to be dark when to theme is light or always?

**Comment by carallo** [comment]
Well actually I have my top bar always dark, so the text should be light the whole time.

 @Vince-bleu I think the menu text depends on the gtk theme I'm using, not the shell theme.

**Comment by gonzaarcr** [comment]
Try uncommenting the line [`set_dark_variation()`](https://github.com/gonzaarcr/Fildem/blob/master/handlers/global_menu.py#L154).

**Comment by carallo** [comment]
> Try uncommenting the line [`set_dark_variation()`](https://github.com/gonzaarcr/Fildem/blob/master/handlers/global_menu.py#L154).

Nice, works perfectly! Thank you!
