### ISSUE TITLE
Some applications don't export their menus first when the app is launched.

### ISSUE THREAD

**Issue by Devansh80** [gonzaarcr/Fildem#35]
I've noticed that some applications don't export their menus first when the app is launched, but it works when I minimize the app and maximize it again or click anywhere in desktop. Overall it's require a **refresh** to export the menus. Here I am mentioning only those applications in which i'm facing this issue.

- Visual Studio Code
- Google Chrome
- Slack Desktop
- Brave Web Browser
- Postman(_Some times_)
- Telegram(_Some times_)

**OS :- Ubuntu 20.04** 

For reference adding some snapshots:-
![104096690-0242d700-52c2-11eb-9399-03a68471cd23](https://user-images.githubusercontent.com/46435891/105359630-ab23f700-5c1d-11eb-9e54-97525927503f.png)
![104097132-23a3c300-52c2-11eb-8a7c-ef4ba3f1c4a3](https://user-images.githubusercontent.com/46435891/105359663-b6772280-5c1d-11eb-8ded-62a7c794bcaa.png)

**Comment by gonzaarcr** [comment]
I’m gonna add a retry delayed since some apps seem to take a while to export the menu.

**Comment by gonzaarcr** [comment]
I added 2 retries with a 2 second wait each on b920ef4. It should be enough for every computer (I hope).

**Comment by Devansh80** [comment]
Hey! @gonzaarcr now it's working fine for me. Thanks

**Comment by Devansh80** [comment]
Hey! @gonzaarcr where i can message you personally, actually i love this extension and want to communicate more regarding this but there are no direct message option available in github.
Well, look at this [link](https://pkgs.org/download/firefox-globalmenu) can it help to make firefox working with global menu.

**Comment by gonzaarcr** [comment]
Send me to gonzaarcr at gmail dot com. Yeah, I haven’t dig into it, but Ubuntu 16 is still supported, and that one has an official patch (from Canonical) with a global menu, but is gonna be unsupported on a few month.

 The link that you provided seems to be from the version 64, and we are on 84, I wouldn’t recommend to use an unsupported version.

 I should check what ppa [Ubuntu Unity](https://ubuntuunity.org) uses, but according to [this post](https://ubuntuunity.org/2020/06/05/hud-globalmenu-firefox) the updates are done manually (also wouldn’t recommend).

**Comment by Devansh80** [comment]
Thanks for your response man :)

**Comment by RodPaDev** [comment]
I would like to add to this issue that all of those apps use chromium.
