### ISSUE TITLE
Lag when cursor enter or leave panel

### ISSUE THREAD

**Issue by kkren** [gonzaarcr/Fildem#37]
I have the extension installed in arch with gnome wayland. When I move my cursor in or out the panel with extension enabled, the cursor will hang on the edge of panel for a second. The problem persist even after I disable the extension. The problem only disappear after I reboot.

https://user-images.githubusercontent.com/23287823/106455582-59098e00-64c7-11eb-8a9a-cfd3c5a74f81.mp4

**Comment by gonzaarcr** [comment]
Is your computer old? I’d bet is Wayland related. There’s no much I can do, but I can remove the event listeners with the configuration `FORCE_SHOW_MENU`.

**Comment by kkren** [comment]
I'm using an I7 6200u with an HD 520 graphic. Most other extensions can run smoothly but this seems to have a significant performance impact. How should I remove the event listeners since I do want to force show the menu?

**Comment by kkren** [comment]
I've tried comment out L261-262 in extension.js, the problem still exist.
