### ISSUE TITLE
run.sh can't detect fuzzysearch and won't run as a result

### ISSUE THREAD

**Issue by ModernMozart** [gonzaarcr/Fildem#4]
Hi!

I'm having issues with the installation. When I try to run "run.sh" it tells me that fuzzysearch isn't found, but when I run pip3 install fuzzysearch the output is

Requirement already satisfied: fuzzysearch in /home/<user>/.local/lib/python3.8/site-packages (0.7.3)
Requirement already satisfied: attrs>=19.3 in /home/<user>/.local/lib/python3.8/site-packages (from fuzzysearch) (20.2.0)

so it's apparently installed, but run.sh can't find it. Any ideas or fixes?
![Untitledscreen](https://user-images.githubusercontent.com/73030322/96347100-2b9def00-1054-11eb-9f8d-56ac505cd5e2.png)

**Comment by gonzaarcr** [comment]
Try runing as user with `bash run.sh` or `chmod u+x run.sh; ./run.sh`.

**Comment by ModernMozart** [comment]
It just sends 4 error messages and then does nothing.

Gtk-Message: 11:27:02.191: Failed to load module "appmenu-gtk-module"
Gtk-Message: 11:27:02.191: Failed to load module "appmenu-gtk-module"
Gtk-Message: 11:27:02.309: Failed to load module "appmenu-gtk-module"
Gtk-Message: 11:27:02.309: Failed to load module "appmenu-gtk-module"

**Comment by gonzaarcr** [comment]
What OS are you using? Follow the instructions on the [readme](https://github.com/gonzaarcr/Fildem/blob/master/README.md#install-modules-for-the-menu), those should work, at least for Ubuntu.

**Comment by ModernMozart** [comment]
Ubuntu, and I got it working. I removed the dependencies and installed them again and it worked

**Comment by ModernMozart** [comment]
It's too far to the right, nearly overlapping with my clock. Is there a way to customize the position?

**Comment by gonzaarcr** [comment]
I made a commit for that just yesterday! I’d apreciate if you can try it out and send me a pic on how it looks. It’s hard to program to all the variety of Linux systems.
