### ISSUE TITLE
Traceback error when running run.sh 

### ISSUE THREAD

**Issue by BrunoCarvalhoAlvim** [gonzaarcr/Fildem#43]
I've dowloaded the repo and moved fildemGMenu@gonza.com to my extensions folder, but wen i run ./run.sh i get a Traceback error form python that says: 

"""
Traceback (most recent call last):
  File "/home/bruno/globalmenu-gnome/Fildem/./command.py", line 6, in <module>
    from handlers.default import HudMenu
  File "/home/bruno/globalmenu-gnome/Fildem/handlers/default.py", line 1, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
"""

I've tried to install these packages with pip, but had no success.

I'm using pop-os 20.10, gnome is 3.38.3

"""
❯ la ~/.local/share/gnome-shell/extensions/
total 28K
drwxrwxr-x 5 bruno bruno 4.0K Mar 20 10:18 caffeine@patapon.info
drwxrwxr-x 4 bruno bruno 4.0K Mar 20 10:20 clipboard-indicator@tudmotu.com
drwxrwxr-x 5 bruno bruno 4.0K Mar 20 13:42 dynamic-panel-transparency@rockon999.github.io
drwxrwxr-x 3 bruno bruno 4.0K Mar 27 14:21 fildemGMenu@gonza.com
drwxrwxr-x 5 bruno bruno 4.0K Mar 26 12:15 floating-dock@nandoferreira_prof@hotmail.com
drwxrwxr-x 6 bruno bruno 4.0K Mar 20 13:37 freon@UshakovVasilii_Github.yahoo.com
drwxrwxr-x 7 bruno bruno 4.0K Mar 26 08:42 sound-output-device-chooser@kgshank.net
."""

**Comment by gonzaarcr** [comment]
`sudo apt install python3-gi`, or if that doesn’t work, also install `sudo apt install python3-gi-cairo gir1.2-gtk-3.0`

**Comment by BrunoCarvalhoAlvim** [comment]
Thanks for the help, but it didn't work for me.

```
Fildem on  master via 🐍 v3.9.2 
❯ sudo apt install python3-gi
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-gi is already the newest version (3.38.0-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

Fildem on master via 🐍 v3.9.2 took 4s 
❯ sudo apt install python3-gi-cairo gir1.2-gtk-3.0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gir1.2-gtk-3.0 is already the newest version (3.24.23-1ubuntu1).
python3-gi-cairo is already the newest version (3.38.0-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

Fildem on master via 🐍 v3.9.2 
❯ ./run.sh                   
Traceback (most recent call last):
  File "/home/bruno/globalmenu-gnome/Fildem/./command.py", line 6, in <module>
    from handlers.default import HudMenu
  File "/home/bruno/globalmenu-gnome/Fildem/handlers/default.py", line 1, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'

Fildem on master via 🐍 v3.9.2 
❯ sudo apt install python3-gi-cairo gir1.2-gtk-3.0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gir1.2-gtk-3.0 is already the newest version (3.24.23-1ubuntu1).
python3-gi-cairo is already the newest version (3.38.0-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

Fildem on master via 🐍 v3.9.2 
❯ ./run.sh                                        
Traceback (most recent call last):
  File "/home/bruno/globalmenu-gnome/Fildem/./command.py", line 6, in <module>
    from handlers.default import HudMenu
  File "/home/bruno/globalmenu-gnome/Fildem/handlers/default.py", line 1, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
```

I think its because i'm using asdf.

```
Fildem on master via 🐍 v3.9.2 
❯ which python
/home/bruno/.asdf/shims/python

Fildem on master via 🐍 v3.9.2 
❯ which -a python
/home/bruno/.asdf/shims/python

Fildem on master via 🐍 v3.9.2 
❯ which -a python3.8
/usr/bin/python3.8
/bin/python3.8
```

python3-gi its only callable by system python (at /usr/bin/python3.8 in my case). I already try to reshim, but had no luck. 
```
❯ python3.8
Python 3.8.6 (default, Jan 27 2021, 15:42:20) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> import gi
>>> sys.executable
'/usr/bin/python3.8'
>>> 

```
I think we can close this issue, the problem is in the configuration of my system.

Thanks for the help.

**Comment by gonzaarcr** [comment]
Maybe try with `python3.8 run.py`
