### ISSUE TITLE
Gnome 40 compatibility

### ISSUE THREAD

**Issue by carallo** [gonzaarcr/Fildem#44]
Hi again @gonzaarcr !

I'm enjoying your extension a lot, have managed to make it work almost perfectly, adjusting it to my needs.
I have a question though, since Gnome 40 has been released and will slowly start to get pushed into various distributions, how is this gonna work with it? Have you thought about issues and/or possible solutions to that, or are you planning of not developing it for Gnome 40? (I really hope not since I am totally fond of global menu and love Fildem!)

Thank you and best wishes!

**Comment by gonzaarcr** [comment]
It works on gnome 40 out of the box. The only think that doesn’t work is the preference window, but it doesn’t break anything. There’s a branch for gnome 40 which at the moment is exactly like main but without preferences.

**Comment by carallo** [comment]
Great, good to know! And what about GTK4? I had read somewhere it would be almost impossible to export menus for GTK4 apps...

**Comment by gonzaarcr** [comment]
Yeap, but I don’t know how much it will affect, most of those apps currently don’t export a menu anyways.

**Comment by carallo** [comment]
Yeah I know, unfortunately. But at least for those that still do, especiallythe ones with a lot of menu entries (such as GIMP or LibreOffice), it's reassuring to me that the menu can still work. I really don't understand how global menu is not more widespread, to me is such an improvement in terms of usability and workflow. Anyway...

Thank you again @gonzaarcr !

**Comment by rosostolato** [comment]
@gonzaarcr is there a way to manually change the settings. I would like to always show the menu for example

**Comment by gonzaarcr** [comment]
Go to the extension apps and press the settings icon.

**Comment by rosostolato** [comment]
@gonzaarcr thank you! It was crashing on gnome 40 but I was using an old version. The new version from git is working just fine.
