### ISSUE TITLE
new problem😭

### ISSUE THREAD

**Issue by 196082** [gonzaarcr/Fildem#45]
I used pip3 install fuzzysearch, but I reported an error in sudo ./run.sh, and it couldn't find the module named "fuzzysearch"

**Comment by gonzaarcr** [comment]
Try without sudo

**Comment by 196082** [comment]
> Try without sudo it shows new errors in the absence of sudo, "namespace bamf not available"

**Comment by gonzaarcr** [comment]
`sudo apt install libbamf3-dev bamfdaemon`

**Comment by 196082** [comment]
> `sudo apt install libbamf3-dev bamfdaemon`

It worked! Thank you so much!
