### ISSUE TITLE
Is there any way to make Fildem support Firefox?

### ISSUE THREAD

**Issue by CleoMenezes** [gonzaarcr/Fildem#47]
![image](https://user-images.githubusercontent.com/54215258/113797776-e8c5f580-971f-11eb-950e-03ef24f278bd.png)

Thanks for the beautiful work.

**Comment by gonzaarcr** [comment]
There’s a patch for Arch. For Ubuntu, you can download it from [here](http://archive.ubuntu.com/ubuntu/pool/main/f/firefox/) and then install it

```
wget http://archive.ubuntu.com/ubuntu/pool/main/f/firefox/firefox_87.0+build3-0ubuntu0.18.04.2_amd64.deb
sudo apt install ./firefox_87.0+build3-0ubuntu0.18.04.2_amd64.deb
sudo apt-mark hold firefox
```

But this will disable updates for the browser.

**Comment by carlosrca** [comment]
What about Fedora is there an alternative? Thanks, good extension 👍
