### ISSUE TITLE
Problems running the ./run.sh command

### ISSUE THREAD

**Issue by guilhermeoliveiralopes** [gonzaarcr/Fildem#50]
Hello, there is a problem, when I run the command ./run.sh in the terminal, nothing happens, it does not appear an error message and does not change the top bar

**Comment by gonzaarcr** [comment]
Have you installed and enabled the extension?

**Comment by guilhermeoliveiralopes** [comment]
Yes

**Comment by gonzaarcr** [comment]
Test an app that you know will have a menu, not all have a menu.

**Comment by guilhermeoliveiralopes** [comment]
Does it work in all applications?

**Comment by gonzaarcr** [comment]
The application has to export its menu. Check the [state of the apps](https://github.com/gonzaarcr/Fildem/wiki/Using#state-of-the-apps)
