### ISSUE TITLE
Not Working in Gnome 40

### ISSUE THREAD

**Issue by JulioCesarS93** [gonzaarcr/Fildem#56]
I can't make it work in archlinux gnome 40

I've added "40" in shell-version of the metadata.json file, so now i can enable the extension. So i've run the run.sh file and opened libreoffice and that made my gnome-shell freeze and i had to restart my pc

**Comment by gonzaarcr** [comment]
Wayland?

**Comment by JulioCesarS93** [comment]
Xorg

**Comment by JulioCesarS93** [comment]
I've just downloaded the last version. When i try to run inithud.sh i get the following error:
Error org.freedesktop.DBus.Error.ServiceUnknown: The name com.gonzaarcr.appmenu was not provided by any .service files

**Comment by JulioCesarS93** [comment]
Downloaded the last version and now it works. Tyvm for this wonderful work
