### ISSUE TITLE
This program locks my keyboard and crashes all the time especially in VS code

### ISSUE THREAD

**Issue by 196082** [gonzaarcr/Fildem#59]

**Comment by gonzaarcr** [comment]
Can you try now?

**Comment by 196082** [comment]
> OS? Gnome version? Xorg/Wayland?

Debian，gnome3.38

**Comment by 196082** [comment]
> Can you try now?
It's just an occasional crash, and it's hard for me to demonstrate it

**Comment by gonzaarcr** [comment]
I‘ve reduced the interaction with the keyboard for Wayland. I‘ll keep teting for Xorg.

**Comment by marzuk-zarir** [comment]
I have same problem....after boot if i select a menu (especially vscode) from global menu my system is freeze and keyboard doesn't work
Os: Ubuntu 20.04
Gnome-shell: 3.38

**Comment by TROMsite** [comment]
It happens to me too, but for like 40s then comes back to life. Happens when I do certain things in Shotwell, like changing the date of a photo.

**Comment by gonzaarcr** [comment]
Does it happen regularly or after a long period of use?

**Comment by marzuk-zarir** [comment]
> Does it happen regularly or after a long period of use?

after 30-40 min

**Comment by gonzaarcr** [comment]
I think it’s fixed. I’m gonna keep testing before doing another relesae.

**Comment by marzuk-zarir** [comment]
> I think it’s fixed. I’m gonna keep testing before doing another relesae.

In my system, this issue is fixed after installing last version.....thnx
