### ISSUE TITLE
KeyError: 'XDG_SESSION_TYPE'

### ISSUE THREAD

**Issue by Kinjutsu00** [gonzaarcr/Fildem#6]
sudo ./run.sh brings this error:

./run.sh: line 3: [: =: unary operator expected
Traceback (most recent call last):
  File "./command.py", line 7, in <module>
    from handlers.default import HudMenu
  File ".../Fildem-master/handlers/default.py", line 16, in <module>
    from utils.menu import WindowActions
  File ".../Fildem-master/utils/menu.py", line 10, in <module>
    from utils.window import WindowManager
  File ".../Fildem-master/utils/window.py", line 18, in <module>
    backend = os.environ['XDG_SESSION_TYPE']
  File "/usr/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'XDG_SESSION_TYPE'

after looking around i edit run.sh in this way:
                                                
#!/bin/bash

if [[ $XDG_SESSION_TYPE == 'x11' ]]; then
        export UBUNTU_MENUPROXY=0; python3 ./command.py
else
        export UBUNTU_MENUPROXY=0; export GDK_BACKEND=x11; python3 ./command.py
fi

but the error persist in part:

Traceback (most recent call last):
  File "./command.py", line 7, in <module>
    from handlers.default import HudMenu
  File ".../Fildem-master/handlers/default.py", line 16, in <module>
    from utils.menu import WindowActions
  File ".../Fildem-master/utils/menu.py", line 10, in <module>
    from utils.window import WindowManager
  File ".../Fildem-master/utils/window.py", line 18, in <module>
    backend = os.environ['XDG_SESSION_TYPE']
  File "/usr/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'XDG_SESSION_TYPE'

**Comment by gonzaarcr** [comment]
Weird, what OS are you running? Give me the output of `lsb_release -a` and `echo $XDG_SESSION_TYPE`

**Comment by Kinjutsu00** [comment]
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

echo $XDG_SESSION_TYPE
x11

**Comment by gonzaarcr** [comment]
I have no idea what’s the problem. Try deleting the python cache, from the folder of this project execute

```find . -name \*.pyc -delete```

and add `export XDG_SESSION_TYPE=$XDG_SESSION_TYPE` on the first line of the run.sh file.

**Comment by Kinjutsu00** [comment]
after that, if i exec run.sh with sudo nothing happens, it gets stuck.

if i run it without sudo i get this:
** (-c:14398): WARNING **: 20:25:43.527: Binding '<Alt>space' failed!
and get stuck...

**Comment by gonzaarcr** [comment]
That error is proper of Wayland, but that says that you are using X11, maybe some compatibility layer? Give me the output of the following, please: 

```
loginctl show-session $(loginctl | grep $(whoami) | awk '{print $1}') -p Type
echo 1. $WAYLAND_DISPLAY 2. $DISPLAY
```

**Comment by Kinjutsu00** [comment]
1) Type=x11
2) 1. 2. :0

**Comment by gonzaarcr** [comment]
The problem is the `sudo`, run without it. The programm won’t have any output, you have to install the extension (just move the folder to the extension folder and activate it) and the menu shows when you have the mouse on the top panel.
