### ISSUE TITLE
Not able to synchronise the menu & panels with Dash to panel

### ISSUE THREAD

**Issue by thecoder-001** [gonzaarcr/Fildem#62]
### Information

- **Operating System**:  
```
Distributor ID:	Ubuntu
Description:	Ubuntu 21.04
Release:	21.04
Codename:	hirsute
```
- **Gnome Shell Version**: 
```
GNOME Shell 3.38.4
```
- **Xorg/Wayland?**:  `Xorg`
- **Apps tested**:   all gtk/qt apps
- **Fildem version**:  `0.6.6`

### What is the current behavior?
While using the extension with `dash to panel` the menu and the items desynchronize and tweaking the button padding from the extension setting doesn't helps.
![image](https://user-images.githubusercontent.com/25097841/116575392-37843b00-a92c-11eb-9021-c9241f1bb083.png)

### Steps to reproduce the problem
  - Download and enable dash to panel from [extensions.gnome.org](https://www.extensions.gnome.org/).
  - Download Fildem & run it.
  - Try to synchronise the menus and panels together by tweaking the button paddings from the extension settings.

### What is the expected behavior?
Menu and the list to remain synchronised with each other.

**Comment by gonzaarcr** [comment]
I changed the place where it appears in 00e33750, it should be more consistent now.

**Comment by thecoder-001** [comment]
That seems to have fixed it. Thanks!
