### ISSUE TITLE
Can't see main menu, can see popups though

### ISSUE THREAD

**Issue by Suor** [gonzaarcr/Fildem#67]
![fildem-no-menu-visible](https://user-images.githubusercontent.com/284103/116818326-0fe3db80-ab95-11eb-9428-0b784ea56b27.png)

### Information

- **Operating System**:  

```console
$ lsb_release -a
LSB Version:    core-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 20.10
Release:    20.10
Codename:   groovy
```

- **Gnome Shell Version**: 

```console
$ apt show gnome-shell | grep Version
Version: 3.38.2-1ubuntu1~20.10.1
```

- **Xorg/Wayland?**: 

Xorg

- **Apps tested**:  

Sublime Text 3

- **Fildem version**:

0.6.6

### What is the current behavior?

Menu doesn't show on mouse hover nor on keyboard shortcut, i.e. `Alt+F`. I see menu popup though.

**Comment by gonzaarcr** [comment]
Is the extension enabled?

**Comment by Suor** [comment]
Oh, missed that, sorry. It appeared once I installed extension.
