### ISSUE TITLE
Only first item visible - "File" and often doesn't work at all

### ISSUE THREAD

**Issue by thatonearchguy** [gonzaarcr/Fildem#7]
Hi, 
This seems like a great extension but it doesn't seem to be working correctly for me. 
It's truncated the application name text permanently, and only the first menu item is visible - ("File").
If I attempt to click on "File" I get an error in run.sh saying:
```
(-c:4904): Gtk-WARNING **: 19:12:18.007: Theme parsing error: gtk.css:6329:10: 'height' is not a valid property name
Gnome HUD: WARNING: () No menu items available!
```
It does not crash however - I wonder if it's some dependency issue or something as I am using arch. Sometimes it refuses to work altogether and cannot see any menu items or name truncation. Would love to see this working as I've migrated to GNOME from KDE due to significantly better touchscreen support and it's the one thing I'm missing. 
Thanks!

**Comment by gonzaarcr** [comment]
First of all, a shamefull selfprom, I also love touchpad gestures and if you like the win10 gesture for changing windows you can try [this other extension](https://github.com/gonzaarcr/touchpad-window-switcher-gnome-ext).

For the problem, you shouldn’t worry about that output, it’s normal, but that doesn’t explain your problem. In what application are you trying? I think I should do a video explaining how this app works.

**Comment by thatonearchguy** [comment]
Thanks for your quick response,
I am attempting most of the applications I commonly use like vscode, Firefox (kde-opensuse-bin) which was compiled with KDE global menu support although have tried with regular Firefox, file manager, libre office etc. 
I turn the extension on and run the script file and if it works then the application name gets truncated and I see the global menu but only the first bit. If I hover over the rest of the top bar however the other menus do drop down occasionally...
I'll try with a different shell theme in case it's causing conflicts.

**Comment by gonzaarcr** [comment]
Oh, I haven’t tested on 3.38, I’m gonna try on a virtual machine.

**Comment by gonzaarcr** [comment]
I installed Arch on a VM and couldn’t install libkeybinder, how did yo do?

**Comment by gonzaarcr** [comment]
Download and try now (I change only two lines so you can also edit it by hand)

**Comment by thatonearchguy** [comment]
I edited the two lines by hand, it seems to be working now! Thanks! 
One question, would it be possible to have the global menu showing by default without having to hover over the top bar? This is how I had it in KDE, I'll have a play around with the extension code if you don't mind to see if I can get this behavior. 
Also many gnome applications are not showing anything in the top bar when I hover over the name - the only applications showing things are VSCode, LibreOffice and Firefox (kde-opensuse-bin variant). Do the GNOME apps not have any global menu items?

**Comment by gonzaarcr** [comment]
Yeah, GNOME apps don’t show anything since they don’t export the menus. It really surprised me seeing gedit export their menus.

For the always showing is easy, just write an early return on `_onPanelLeave`.
