### ISSUE TITLE
In ubuntu

### ISSUE THREAD

**Issue by spideyO0** [gonzaarcr/Fildem#72]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'fildem'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'fildem'

I got this error what to do

**Comment by CMU-Yi** [comment]
On Ubuntu 20.04, Gnome version 3.36. 

I got a similar error:

```Failed to load module "unity-gtk-module"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'fildem'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'fildem'
```

When I try to `sudo apt install unity-gtk-module`, another error occurred:
```Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package unity-gtk-module is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'unity-gtk-module' has no installation candidate
```


Anything suggestion?

**Comment by DuttaAB-dev** [comment]
Do you have appmenu-gtk3-module installed?

**Comment by CMU-Yi** [comment]
> Do you have appmenu-gtk3-module installed?

Yes, that was already installed.

**Comment by gonzaarcr** [comment]
@spideyO0 can you provide the steps that you did?

@CMU-Yi If you install it through the .deb file you don’t need to install anything.

**Comment by spideyO0** [comment]
this problem is caused by anaconda if u remove anaconda fildem will work just fine it worked for me

**Comment by zhoyifan** [comment]
So is there any way to let anaconda and fildem coexist? For instance, specifically assign the pip and python command directory for fildem, and do not modify the default pip and python command.

**Comment by maacpiash** [comment]
I'd like to get a solution to this problem, too. I need Anaconda for school, and I'd also like to continue using Fildem.
