### ISSUE TITLE
Firefox Oddities

### ISSUE THREAD

**Issue by jannuary** [gonzaarcr/Fildem#8]
### Description 
Here's how the global menu looks with Firefox, with the appmenu patch applied (firefox-appmenu on the AUR): 
![image](https://user-images.githubusercontent.com/27908024/97426059-7ddceb00-1945-11eb-8602-54708600c319.png)
Clicking on "Label Empty" after some time reveals what should be in the menu bar: File, Edit, View, etc., each having their own additional dropdown.
### Steps to reproduce
1. Install firefox-appmenu from the AUR on Arch
2. Run the run.sh script with the extension installed
### Desired behavior
Global menubar should show File, Edit, View, etc. options directly.

**Comment by gonzaarcr** [comment]
Can you guide me to install that Firefox patch on Arch?

**Comment by jannuary** [comment]
> Can you guide me to install that Firefox patch on Arch?

 Either use an AUR helper like [yay](https://computingforgeeks.com/yay-best-aur-helper-for-arch-linux-manjaro/) or download and build manually from [here.](https://aur.archlinux.org/packages/firefox-appmenu/)

**Comment by carallo** [comment]
Do you know how to use this with Firefox in Ubuntu 20?

**Comment by gonzaarcr** [comment]
I couldn’t find any good repo for Ubuntu with the menu. There’s a distro Ubuntu Unity still with the Unity environmnent that has the patched version, but the version is locked so I didn’t dig any further because I prefer security. I don’t know if KDE has some patched version.

**Comment by carallo** [comment]
> I couldn’t find any good repo for Ubuntu with the menu. There’s a distro Ubuntu Unity still with the Unity environmnent that has the patched version, but the version is locked so I didn’t dig any further because I prefer security. I don’t know if KDE has some patched version.

Ahh I understand! The package name is firefox-appmenu? I'll try to have a look around

**Comment by gonzaarcr** [comment]
I think this magically fix with the electron update. Can you confirm @jannuary?

**Comment by skewty** [comment]
Mozilla / Firefox doesn't use Electron.  Why would an Electron update fix it?

**Comment by gonzaarcr** [comment]
They both export their menus with the same API and (it seems) both use some weird “lazy” export, so you have to retrieve the menu recursively; I think that’s why that update helped.
