### ISSUE TITLE
Global menu is not showing

### ISSUE THREAD

**Issue by marzuk-zarir** [gonzaarcr/Fildem#85]
Ubuntu 21( xorg )
gnome-shell: 3.38
global is not showing in firefox but other applications works fine

![Screenshot from 2021-06-08 12-11-29](https://user-images.githubusercontent.com/75979581/121132239-b4bb9d80-c852-11eb-8875-cf3192a70f06.png)

**Comment by thecoder-001** [comment]
Known issue. Check [here](https://github.com/gonzaarcr/Fildem/wiki/Using#state-of-the-apps).

**Comment by DuttaAB-dev** [comment]
> Ubuntu 21( xorg )
> gnome-shell: 3.38
> global is not showing in firefox but other applications works fine
> 
> ![Screenshot from 2021-06-08 12-11-29](https://user-images.githubusercontent.com/75979581/121132239-b4bb9d80-c852-11eb-8875-cf3192a70f06.png)
Was it installed using flatpak?

**Comment by marzuk-zarir** [comment]
> > Ubuntu 21( xorg )
> > gnome-shell: 3.38
> > global is not showing in firefox but other applications works fine
> > ![Screenshot from 2021-06-08 12-11-29](https://user-images.githubusercontent.com/75979581/121132239-b4bb9d80-c852-11eb-8875-cf3192a70f06.png)
> > Was it installed using flatpak?

no....i was download with release note and gnome-shell extension

**Comment by DuttaAB-dev** [comment]
> > > Ubuntu 21( xorg )
> > > gnome-shell: 3.38
> > > global is not showing in firefox but other applications works fine
> > > ![Screenshot from 2021-06-08 12-11-29](https://user-images.githubusercontent.com/75979581/121132239-b4bb9d80-c852-11eb-8875-cf3192a70f06.png)
> > > Was it installed using flatpak?
> 
> no....i was download with release note and gnome-shell extension

No, I mean, was the firefox browser installed using flatpak?

**Comment by Benjimanrich** [comment]
> Known issue. Check [here](https://github.com/gonzaarcr/Fildem/wiki/Using#state-of-the-apps).

see what @thecoder-001 said

**Comment by marzuk-zarir** [comment]
> No, I mean, was the firefox browser installed using flatpak?
no.....i was downloaded firefox from their official site

**Comment by gonzaarcr** [comment]
There was a patched version for Unity, but now that it’s gone I don’t know its state. There was some discussion [here](https://github.com/gonzaarcr/Fildem/issues/35#issuecomment-766961926).
