### ISSUE TITLE
Is this repo maintained any more?

### ISSUE THREAD

**Issue by DuttaAB-dev** [gonzaarcr/Fildem#87]
There has been no updates to the repo for about a month now and neither has the developer been active in that time. So, I was wondering about the future of this project.

**Comment by anishkumar127** [comment]
yeah. that is an awesome project. we want to improvement in this project <3

**Comment by gonzaarcr** [comment]
I will try to be close but at the same time not-that-close. Changing task everyday really kills ones inertia. Also, working with constantly changing stuff like gnome 40 and Wayland it’s really hard, I better wait (I wonder what will Ubuntu do with those two).

**Comment by DuttaAB-dev** [comment]
Well for ubuntu, I think they are gonna shift to gnome 42/41 or what ever the next version is gonna be for the upcoming release. I really wish I could help in this project in one way or the other, its really great and donno why the gnome devs never considered adding this to their ux.
