### ISSUE TITLE
Can't install the modules

### ISSUE THREAD

**Issue by livioavalle** [gonzaarcr/Fildem#9]
When running: `sudo apt install unity-gtk2-module unity-gtk3-module appmenu-gtk3-module`
I get that:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
unity-gtk2-module is already the newest version (0.0.0+18.04.20171202-0ubuntu2).
unity-gtk3-module is already the newest version (0.0.0+18.04.20171202-0ubuntu2).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 appmenu-gtk3-module : Conflicts: appmenu-gtk3
 unity-gtk3-module : Conflicts: appmenu-gtk3
E: Unable to correct problems, you have held broken packages.
```

And when i try to run the run.sh i get:
```
Gtk-Message: 21:45:56.048: Failed to load module "appmenu-gtk-module"
Gtk-Message: 21:45:56.219: Failed to load module "appmenu-gtk-module"
```
How can i fix?

**Comment by gonzaarcr** [comment]
20.04 or 20.10?

**Comment by livioavalle** [comment]
20.10

**Comment by gonzaarcr** [comment]
Try to update and clean

```
sudo apt-get update
sudo apt-get clean
sudo apt-get autoremove
sudo apt  install -f
sudo dpkg --configure -a
sudo apt-get install -f
```

**Comment by livioavalle** [comment]
> 20.04 or 20.10?

And then this? 
`sudo apt install unity-gtk2-module unity-gtk3-module appmenu-gtk3-module`

**Comment by livioavalle** [comment]
I tried to do what you suggested but it did not work, I still have the same error

**Comment by gonzaarcr** [comment]
- Yes, this is still a work in progress
 - Change[`FORCE_SHOW_MENU`](https://github.com/gonzaarcr/Fildem/blob/master/fildemGMenu%40gonza.com/extension.js#L28) to true to always show the menu.

**Comment by livioavalle** [comment]
> * Yes, this is still a work in progress
> * Change[`FORCE_SHOW_MENU`](https://github.com/gonzaarcr/Fildem/blob/master/fildemGMenu%40gonza.com/extension.js#L28) to true to always show the menu.

Thank you, anyway i fixed the the installation of `unity-gtk2-module unity-gtk3-module appmenu-gtk3-module` using aptitude instead of apt
