### ISSUE TITLE
When clicking a option with check-able box ,it works correctly  but it doesn't change its state  (on/off).

### ISSUE THREAD

**Issue by gsingh704** [gonzaarcr/Fildem#91]
### Information

- **Operating System**:  Manjaro KDE
- **Gnome Shell Version**: 3.38.4
- **Xorg/Wayland?**: X11
- **Apps tested**:   Firefox, terminal , kdenlive, LibreOffice
- **Fildem version**: latest

### What is the current behavior?
When clicking a option with check-able box ,it works correctly  but it doesn't change its state  (on/off).
For example in terminal if I click on read only , terminal changes to read only but the option remain with a "tick" in the box. It change if you change the app and then re-open the same app

### Steps to reproduce the problem
Open gnome-terminal
Click on Read-only
See if it change the box status change or not
change app 
now see the read-only option in menu

### What is the expected behavior?
Change the state of the box according if the option is on or not at the same time not when changing apps

**Comment by gonzaarcr** [comment]
I’m working on this, but some applications don’t send the updated event. I might to just refresh evrything.

**Comment by gonzaarcr** [comment]
I’ve created an issue (#94) to seek for external help and try to fix this issue. I will close this one.
