### ISSUE TITLE
Issue with Jetbrain IDE [Flatpak]

### ISSUE THREAD

**Issue by Bearbobs** [gonzaarcr/Fildem#97]
I have the same no global menu issue with both datagrip and pycharm, works fine for other flatpaks like postman and vscode
I have installed java runtime plugin in both the IDE's.

Is this issue because of flatpaks? i can see it supported in the wiki

using POP OS 20.04(based on ubuntu) + X11 + gnome 3.36

**Comment by osieltorres** [comment]
Same happens to me, I got global menu working fine until I open any Jetbrains based IDE, then it does not work anymore though I can still see the menu on top panel.

**Comment by miguel-siqueira-reis** [comment]
i have the same problem

**Comment by Bearbobs** [comment]
use deb package or from JetBrains toolbox

**Comment by aliyazdi75** [comment]
@Bearbobs 
I installed pycharm from jetbrains website and till having this issue. But my snap android-studio works well. Can you describe what did you do to make it work?
